-- MySQL Script generated by MySQL Workbench
-- Thu Oct 27 15:46:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sistemasrrhh
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sistemasrrhh` ;

-- -----------------------------------------------------
-- Schema sistemasrrhh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemasrrhh` DEFAULT CHARACTER SET utf8mb4 ;
USE `sistemasrrhh` ;

-- -----------------------------------------------------
-- Table `sistemasrrhh`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemasrrhh`.`carrera` (
  `CARid` INT NOT NULL AUTO_INCREMENT,
  `CARnombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`CARid`),
  UNIQUE INDEX `carNombre_UNIQUE` (`CARnombre` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sistemasrrhh`.`distrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemasrrhh`.`distrito` (
  `DISTid` INT NOT NULL AUTO_INCREMENT,
  `DISTnombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`DISTid`),
  UNIQUE INDEX `distNombre_UNIQUE` (`DISTnombre` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sistemasrrhh`.`experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemasrrhh`.`experiencia` (
  `EXPid` INT NOT NULL AUTO_INCREMENT ,
  `EXPcant` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EXPid`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sistemasrrhh`.`puesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemasrrhh`.`puesto` (
  `PSTid` INT NOT NULL AUTO_INCREMENT ,
  `PSTnombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PSTid`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sistemasrrhh`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemasrrhh`.`reserva` (
  `RESid` INT NOT NULL AUTO_INCREMENT ,
  `RESdesc` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`RESid`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sistemasrrhh`.`dato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemasrrhh`.`dato` (
  `DATid` INT NOT NULL AUTO_INCREMENT,
  `DATnombre` VARCHAR(80) NOT NULL,
  `DATcel` INT NOT NULL,
  `DATedad` INT NULL DEFAULT NULL,
  `CARid` INT NOT NULL,
  `DISTid` INT NOT NULL,
  `DATfech` DATE,
  `DATexpt` VARCHAR(45) NULL DEFAULT NULL,
  `RESid` INT NOT NULL,
  `EXPid` INT NOT NULL,
  `DATcoment` VARCHAR(225) NULL DEFAULT NULL,
  `DATestado` VARCHAR(45) NULL DEFAULT NULL,
  `PSTid` INT NOT NULL,
  PRIMARY KEY (`DATid`),
  UNIQUE INDEX `datCel_UNIQUE` (`DATcel` ASC) ,
  INDEX `CARid_idx` (`CARid` ASC) ,
  INDEX `DISTid_idx` (`DISTid` ASC) ,
  INDEX `RESid_idx` (`RESid` ASC) ,
  INDEX `EXPid_idx` (`EXPid` ASC) ,
  INDEX `FK_PSTid_idx` (`PSTid` ASC) ,
  CONSTRAINT `FK_CARid`
    FOREIGN KEY (`CARid`)
    REFERENCES `sistemasrrhh`.`carrera` (`CARid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_DISTid`
    FOREIGN KEY (`DISTid`)
    REFERENCES `sistemasrrhh`.`distrito` (`DISTid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_EXPid`
    FOREIGN KEY (`EXPid`)
    REFERENCES `sistemasrrhh`.`experiencia` (`EXPid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_PSTid`
    FOREIGN KEY (`PSTid`)
    REFERENCES `sistemasrrhh`.`puesto` (`PSTid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_RESid`
    FOREIGN KEY (`RESid`)
    REFERENCES `sistemasrrhh`.`reserva` (`RESid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sistemasrrhh`.`archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemasrrhh`.`archivo` (
  `ARCid` INT NOT NULL AUTO_INCREMENT,
  `ARCnombre` VARCHAR(150) NOT NULL,
  `ARCpdf` LONGBLOB NOT NULL,
  `DATid` INT NOT NULL,
  PRIMARY KEY (`ARCid`),
  INDEX `FK_ARCid_idx` (`DATid` ASC) ,
  CONSTRAINT `FK_ARCid`
    FOREIGN KEY (`DATid`)
    REFERENCES `sistemasrrhh`.`dato` (`DATid`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
